services:
  ollama:
    image: ollama/ollama:latest
    container_name: erc8004-ollama
    restart: unless-stopped
    ports:
      - "${OLLAMA_HOST_PORT:-11434}:11434"
    volumes:
      - ollama-data:/root/.ollama
      - ./docker/ollama-entrypoint.sh:/usr/local/bin/ollama-entrypoint.sh:ro
    entrypoint: ["/usr/local/bin/ollama-entrypoint.sh"]
    environment:
      - OLLAMA_MODEL=${OLLAMA_MODEL:-gemma3:4b}
      - OLLAMA_BOOTSTRAP_MODELS=${OLLAMA_BOOTSTRAP_MODELS:-}

  agent:
    build:
      context: .
    image: erc8004-agent:local
    env_file:
      - docker/.env.docker
    environment:
      STATE_DIR: /app/state
      PYTHONPATH: /app
    command: ["/app/docker/agent-entrypoint.sh"]
    ports:
      - "${AGENT_HOST_PORT:-8000}:8000"
    volumes:
      - agent-state:/app/state
    restart: unless-stopped
    depends_on:
      - ollama

  scheduler:
    image: erc8004-agent:local
    depends_on:
      agent:
        condition: service_started
    env_file:
      - docker/.env.docker
    environment:
      STATE_DIR: /app/state
      PYTHONPATH: /app
    command: ["/app/docker/scheduler-entrypoint.sh"]
    volumes:
      - agent-state:/app/state
    restart: unless-stopped

volumes:
  agent-state:
  ollama-data:
